stages:
  - build
  - test

variables:
  CI_REGISTRY_USER: $CI_REGISTRY_USER
  CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD

packaging:
  stage: build
  image: docker:dind
  services:
    - ubuntu:latest
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - apt-get update && apt-get install -y curl bash
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> build.env
    - depot login --token $DEPOT_PROJECT_TOKEN
    - depot build-push --project $DEPOT_PROJECT_ID --context . --file ./Dockerfile --tags "registry.gitlab.com/registry2092427/composer-php:v${CI_COMMIT_REF_NAME}-php${CI_JOB_NAME}-alpine" --push --build-arg "VCS_REF=${CI_COMMIT_SHA}" --build-arg "BUILD_DATE=$(cat build.env)" --build-arg "PHP_VERSION=${CI_JOB_NAME}" --build-arg "COMPOSER_VERSION=2" --build-arg "IMAGE_TAG=registry.gitlab.com/registry2092427/composer-php:v${CI_COMMIT_REF_NAME}-php${CI_JOB_NAME}-alpine"

packaging_matrix:
  stage: build
  image: docker:dind
  services:
    - "php:${PHP_VERSION}"
  variables:
    PHP_VERSION: ${PHP_VERSION}
    COMPOSER_VERSION: "2"
  parallel:
    matrix:
      - PHP_VERSION: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
  script:
    - apt-get update && apt-get install -y git curl unzip bash
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> build.env
    - depot login --token $DEPOT_PROJECT_TOKEN
    - depot build-push --project $DEPOT_PROJECT_ID --context . --file ./Dockerfile --tags "registry.gitlab.com/registry2092427/composer-php:v${CI_COMMIT_REF_NAME}-php${PHP_VERSION}-alpine" --push --build-arg "VCS_REF=${CI_COMMIT_SHA}" --build-arg "BUILD_DATE=$(cat build.env)" --build-arg "PHP_VERSION=${PHP_VERSION}" --build-arg "COMPOSER_VERSION=2" --build-arg "IMAGE_TAG=registry.gitlab.com/registry2092427/composer-php:v${CI_COMMIT_REF_NAME}-php${PHP_VERSION}-alpine"

components:
  stage: test
  image: "registry.gitlab.com/registry2092427/composer-php:v${PHP_VERSION}-php${COMPOSER_VERSION}-alpine"
  parallel:
    matrix:
      - PHP_VERSION: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
        COMPOSER_VERSION: ["2"]
  script:
    - cat /etc/os-release
    - composer --version
    - php --version
    - simple-phpunit --version
    - rector -V
    - phpstan --version
    - psalm --version
    - php-cs-fixer --version
    - phpcs --version
    - phpmd --version
    - if [ "${PHP_VERSION}" \>= "7.3" ]; then phpcpd --version; fi
  needs:
    - packaging
